#
#  src/makefile.osf1
#
#  Copyright(C) 2026 - MT
#
#  Operating-system specific makefile for Tru64 UNIX.  Defines the compiler
#  and linker settings before invoking a common build.
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  29 Aug 26         - Initial version - MT
#

CC	= cc
LANG	= $(shell (echo $$LANG | cut -f 1 -d '.'))
CFLAGS	= -D__osf__
LDFLAGS	=
LDLIBS	= -lX11 -lXext -lm -lrt

include makefile.all
